### PR TITLE
Fix make depend without cuda

### PR DESCRIPTION
**Pull request by nshmyrev**
Currently `make depend` without cuda is broken. Originally broken in 5de039aeaacb90241d0362f113eeb88c5c46943d 

```
shmyrev@kappa ~/t/kaldi/src/cudadecoderbin $ make depend
rm -f .depend.mk
g++ -M -std=c++14 -I.. -isystem /home/shmyrev/t/kaldi/tools/openfst-1.7.2/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/shmyrev/t/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g batched-wav-nnet3-cuda2.cc batched-wav-nnet3-cuda.cc batched-wav-nnet3-cuda-online.cc >> .depend.mk
batched-wav-nnet3-cuda-online.cc:23:2: error: #error CUDA support must be configured to compile this binary.
   23 | #error CUDA support must be configured to compile this binary.
      |  ^~~~~
batched-wav-nnet3-cuda-online.cc:31:10: fatal error: cuda.h: No such file or directory
   31 | #include <cuda.h>
      |          ^~~~~~~~
compilation terminated.
../makefiles/default_rules.mk:149: recipe for target 'depend' failed
make: *** [depend] Error 1
```

### CODE REVIEW

**Comment by nshmyrev** [comment]
Also https://github.com/kaldi-asr/kaldi/pull/4506

**Comment by danpovey** [comment]
LGTM..

**Comment by kkm000** [comment]
Wait, something is wrong here. I recently made the change that you're reversing here. And `#if VAR` is very ancient idiomatic check. It is false if VAR is undefined or defined to 0. Otherwise, it succeeds. 

If this change fixes the issue, whatever it is, it means that we _define_ `HAVE_CUDA` to _something other than 1_ to say we do not HAVE_CUDA. This makes no sense. Something is very wrong elsewhere.

**Comment by kkm000** [comment]
This is what I get in kaldi.mk with CUDA:
```
CXXFLAGS += -DHAVE_CUDA ...

CUDA_FLAGS = .... -DHAVE_CUDA \
```
By default, -D without a = set the macro to 1. Let me try to repro.

**Comment by kkm000** [comment]
Yeah, I understand what's going on, but not quite. Without CUDA enabled, we do not compile these files. Why do we propagate the `depend` target onto them then? I think it's a makefile error.

**Comment by kkm000** [comment]
gmake is a pig. I'll fix configure and makefiles.

**Comment by kkm000** [comment]
I came up with a root issue fix. @nshmyrev, PTAL.

**Comment by nshmyrev** [comment]
Great, thank you
