### ISSUE TITLE
Error instaling faster-RNNLM

### ISSUE THREAD

**Issue by anavc94** [kaldi-asr/kaldi#2413]
Hello,

I am having some issues installing faster-RNNLM in Ubuntu 16.04. As the instrucction suggests, I run the script extras/install_faster_rnnlm.sh but the output says:

``Installing Faster RNNLM
Already up-to-date.
Folder 'eigen3' already exists. Exiting
nvcc cuda_softmax.cu -c -Xcompiler "-O3 -march=native -funroll-loops" -o cuda_softmax.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
Makefile:60: recipe for target 'cuda_softmax.o' failed
make: *** [cuda_softmax.o] Error 1

I've been reading something about the compiler, so my version is:

gcc --version

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I've installed CUDA toolkit 9.0 (with the deb local option because the .run was giving me a lot of problems).
Could you please help me?

Thanks!

Edit: I've tried to compile with gcc-4.8 and g++-4.8 but the same error appears on screen.

**Comment by danpovey** [comment]
You probably shouldn't be installing that.
Kaldi now has inbuilt RNNLM tools that are faster to train than
faster_rnnlm and also give better results, I believe.
e.g. see egs/swbd/s5c/local/rnnlm/run_tdnn_lstm.sh.

Dan
