### ISSUE TITLE
Cuda 11.1 and RTX ampere speed inconsistent

### ISSUE THREAD

**Issue by qmmn** [kaldi-asr/kaldi#4291]
Hello,

Ater trading RTX 2080ti for RTX 3080, I had to pull the master code and compile with cuda 11.1 to make it work again, because the old kaldi (pull from 2018) spilled compilation errors with cuda 11.

But performance per iteration (pass) is unexpected in rnnlm training:

- The 3080 ran 2x faster than 2080ti in  chain tdnn training, but did 4x slower in rnnlm training compared to the 2080ti.

My settings:
- Ubuntu 20.04, gcc 9.3, cuda 11.1
- CUDA_ARCH = -gencode arch=compute_86,code=sm_86
- All other configs and parameters remain default.

Same things happened for cuda 11.0 with PTX code.

Is it a performance problem or just unsupported? Any suggestion for me?

Thanks.

**Comment by danpovey** [comment]
You could try running one training job from each with --verbose=1, which
causes a bunch of times-taken of CUDA kernels to be printed at the end,
and see if any kernel stands out as having different speed.
You'll have to select an iteration for which the input model exists.  You
can see the commands at the top of the log files.

**Comment by qmmn** [comment]
I skim 11MB of text for the test you mentioned, and here's the log (rnnlm training pass 1) for CUDA kernels on RTX 3080 (I no longer have the 2080ti, it's traded for this 3080):

[cudevice profile]
CuVectorBase::Floor	0.257802s
CopyRowsFromVec	0.30483s
SymAddMat2	0.306427s
CuVector::Resize	0.331764s
AddDiagMatMat	0.335986s
CuMatrix::Resize	0.34434s
Sum	0.345257s
AddMat	0.495216s
CuMatrix::SetZero	0.605833s
TraceMatMat	0.687848s
BackpropLstmNonlinearity	0.791416s
CopyToVec	0.833854s
AddMatMat	**11.1038s**
AddSmatMat	**46.6874s**
CuMatrixBase::CopyFromMat(from other CuMatrixBase)	**48.5806s**
Total GPU time:	115.292s (may involve some double-counting)
-----
LOG (rnnlm-train[5.5]:PrintMemoryUsage():cu-allocator.cc:368) Memory usage: 186389248/4758437888 bytes currently allocated/total-held; 91/14 blocks currently allocated/free; largest free/allocated block sizes are 42991616/4369996544; time taken total/cudaMalloc is 0.12679/0.00411987, synchronized the GPU 2071 times out of 78852 frees; device memory info: free:4536M, used:5481M, total:10018M, free/total:0.452838maximum allocated: 858933504current allocated: 186389248
# Accounting: time=71 threads=1
# Ended (code 0) at Mon Oct 12 08:57:32 EDT 2020, elapsed time 71 seconds

The outstanding operations are AddMatMat, AddSmatMat, and CuMatrixBase::CopyFromMat which took 85% of the GPU time.Is this abnormal? And could it be fixed overnight?

**Comment by qmmn** [comment]
Sorry for "closing and re-opening" the issue
I mis-click the button

**Comment by jtrmal** [comment]
the idea was to compare these speed with 2080 card
y.

**Comment by qmmn** [comment]
@jtrmal 
Then it's a stalemate for me now.
I won't be able to get back any 2080ti anytime soon.

**Comment by qmmn** [comment]
@danpovey 
Not yet running gdb, but by digging through the entire rnnlm codebase, I found the only place where **CuMatrixBase::CopyFromMat** gets called is in the file **rnnlm-example-utils.cc**

Call-stack could be:
```
RnnlmCoreTrainer::ProcessOutput
  |__ ProcessRnnlmOutput
           |__ ProcessRnnlmOutputNoSampling / ProcessRnnlmOutputNoSamplingBatched
                     |___ CuMatrixBase::CopyFromMat
```
And the snippet itself, which calls **CuMatrixBase::CopyFromMat**, is denoted with quite expressing words:
```
if (objf_den_exact) {
    // This code is not as optimized as it could be, but we don't take this
    // branch in training so efficiency doesn't matter as much.
    // The 'exact' denominator is the log of the sum of the
    // words' probs.

    // the -1 is to remove epsilon.
    CuMatrix<BaseFloat> word_probs(nnet_output.NumRows(),
                                   num_words - 1, kUndefined);
    word_probs.CopyFromMat(word_logprobs.ColRange(1, num_words - 1));
    word_probs.ApplyExpLimited(-80.0, 80.0);
    CuVector<BaseFloat> row_sums(nnet_output.NumRows());
    row_sums.AddColSumMat(1.0, word_probs, 0.0);
    row_sums.ApplyLog();
    BaseFloat ans = -VecVec(row_sums, minibatch.output_weights);
    *objf_den_exact =  ans;
    if (fabs(ans) > 1.0 * nnet_output.NumRows()) {
      KALDI_WARN << "Big den objf "  << ans;
    }
  }
```
I wonder whether it gives any hint? Or I'll try the GDB catching.

And by the way, here's the log from pass 20 of chain tdnn training on RTX 3080. In this task, it runs 2x faster than the 2080ti as expected, and **CuMatrixBase::CopyFromMat** only took **3.72353s**:
```
[cudevice profile]
Heaviside	1.03744s
Sum	1.11882s
CuArray::SetZero	1.20134s
CopyFromMat	1.21967s
Scale	1.25967s
AddVecToRows	1.38402s
AddMat	1.65159s
CuMatrix::Resize	1.73177s
AddDiagMatMat	2.19086s
CuMatrix::SetZero	2.30341s
AddRowSumMat	2.41373s
CopyToVec	2.8257s
TraceMatMat	3.30326s
CuMatrixBase::CopyFromMat(from other CuMatrixBase)	3.72353s
AddMatMat	14.4301s
Total GPU time:	54.5824s (may involve some double-counting)

LOG (nnet3-chain-train[5.5]:PrintMemoryUsage():cu-allocator.cc:368) Memory usage: 35463936/4531945472 bytes currently allocated/total-held; 131/4 blocks currently allocated/free; largest free/allocated block sizes are 2056192/4051398912; time taken total/cudaMalloc is 0.30573/0.00387311, synchronized the GPU 0 times out of 224501 frees; device memory info: free:4320M, used:5694M, total:10014M, free/total:0.431368maximum allocated: 931165440current allocated: 35463936
LOG (nnet3-chain-train[5.5]:main():nnet3-chain-train.cc:101) Wrote raw model to exp/chain_cleaned/tdnn1g_sp_bi/21.1.raw
Accounting: time=58 threads=1
Ended (code 0) at Mon Oct  5 02:32:02 EDT 2020, elapsed time 58 seconds
```

QM.

**Comment by danpovey** [comment]
But it was training that was slow and the comment says that branch isn't
taken in training.  Perhaps you had an unusual option (or a very large
vocabulary).
Showing the entire training log file would be helpful. or at least head and
tail.

**Comment by qmmn** [comment]
@danpovey 
Here's the log on training pass 80 of both the RTX 3080 (today) and RTX 2080ti (back in August when I was still holding it). Both are put on the same dataset (1.2GB) and configuration:

[train.80.1-RTX3080.log](https://github.com/kaldi-asr/kaldi/files/5371828/train.80.1-RTX3080.log)
[train.80.1-RTX2080ti.log](https://github.com/kaldi-asr/kaldi/files/5371829/train.80.1-RTX2080ti.log)

Vocab sizes are 10k (on RTX-3080) and 90k (on RTX-2080ti). But the 2080ti only took 375s per pass while the 3080 is devouring 1114s likewise.

I'm still painfully waiting for the 3080 to pass each iteration right now, almost 20 minutes/pass T_T
I'm so sad, the 3080 is now even worse than the old days of 1080ti where only 557s is need per iter T___T

**Comment by danpovey** [comment]
do the gdb thing.  i think it shouldnt reach that line you.showed me.
might be in nnet3.

**Comment by qmmn** [comment]
@danpovey 

I setup gdb trying interrupt **CuMatrixBase::CopyFromMat**  but it's strange that it always ends up at **TraceMatMat** or **CopyToVec**:

![1](https://user-images.githubusercontent.com/15570970/95888494-23da0400-0d4f-11eb-9670-11b82df302bf.jpg)

After like 30 mins or so without any luck, I went into the code cu-matrix.cc to setup a trap there, recompiled, and ran again:
- First is to print out text to check whether **CuMatrixBase::CopyFromMat** got any calls

![2](https://user-images.githubusercontent.com/15570970/95888683-66034580-0d4f-11eb-971a-9896263420cc.jpg)

- And second is to print out the stack trace directly there 

![3](https://user-images.githubusercontent.com/15570970/95888757-80d5ba00-0d4f-11eb-83b6-468e3ae8251f.jpg)

Now, things are even weird from the 2nd image that  **CuMatrixBase::CopyFromMat** got tons of invocation before each LOG-line. And the last image is quite confused when run with both gdb with print-stack-trace in code, so I turn off gdb leaving print-stack-trace alone. 

```
COPYFROMMAT - Overloaded Function 1
......

COPYFROMMAT - Overloaded Function 1
 0# void kaldi::CuMatrixBase<float>::CopyFromMat<float>(kaldi::CuMatrixBase<float> const&, kaldi::MatrixTransposeType) in /home/utic/kaldi/src/lib/libkaldi-cudamatrix.so
 1# kaldi::CuMatrix<float>::CuMatrix(kaldi::CuMatrix<float> const&, kaldi::MatrixTransposeType) in /home/utic/kaldi/src/lib/libkaldi-cudamatrix.so
 2# kaldi::nnet3::OnlineNaturalGradient::OnlineNaturalGradient(kaldi::nnet3::OnlineNaturalGradient const&) in /home/utic/kaldi/src/lib/libkaldi-nnet3.so
 3# kaldi::nnet3::NaturalGradientAffineComponent::NaturalGradientAffineComponent(kaldi::nnet3::NaturalGradientAffineComponent const&) in /home/utic/kaldi/src/lib/libkaldi-nnet3.so
 4# kaldi::nnet3::NaturalGradientAffineComponent::Copy() const in /home/utic/kaldi/src/lib/libkaldi-nnet3.so
 5# kaldi::nnet3::Nnet::Nnet(kaldi::nnet3::Nnet const&) in /home/utic/kaldi/src/lib/libkaldi-nnet3.so
 6# kaldi::rnnlm::RnnlmCoreTrainer::RnnlmCoreTrainer(kaldi::rnnlm::RnnlmCoreTrainerOptions const&, kaldi::rnnlm::RnnlmObjectiveOptions const&, kaldi::nnet3::Nnet*) in /home/utic/kaldi/src/lib/libkaldi-rnnlm.so
 7# kaldi::rnnlm::RnnlmTrainer::RnnlmTrainer(bool, kaldi::rnnlm::RnnlmCoreTrainerOptions const&, kaldi::rnnlm::RnnlmEmbeddingTrainerOptions const&, kaldi::rnnlm::RnnlmObjectiveOptions const&, kaldi::CuSparseMatrix<float> const*, kaldi::CuMatrix<float>*, kaldi::nnet3::Nnet*) in /home/utic/kaldi/src/lib/libkaldi-rnnlm.so
 8# main in rnnlm-train
 9# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
10# _start in rnnlm-train

COPYFROMMAT - Overloaded Function 1
.......

```

Any clues? Or should I press for more information somehow?

**Comment by danpovey** [comment]
Forgot to mention, you have to do it with --verbose=1 so it will sync the
GPU after each command, otherwise the times it's waiting on the CPU
side don't reflect GPU time taken.

**Comment by qmmn** [comment]
Add "--verbose=1" makes it almost always stopping at **CuMatrixBase::CopyFromMat** but by **kaldi::CuDevice::AccuProfile**:

![1](https://user-images.githubusercontent.com/15570970/95952163-9be31100-0dc5-11eb-95ff-180a6206ae73.jpg)

Anything strange?

**Comment by danpovey** [comment]
Looks like our transpose is slow.
Could do you me a favor: could you please go to this link
https://www.nvidia.com/content/cudazone/cuda_sdk/Linear_Algebra.html#transpose
and include an image of the text in this chat?   I'm unable to load that
website.  (I always have trouble with the NVidia online docs,
I think it's the  general bloat).

Dan

**Comment by qmmn** [comment]
@danpovey 
Here's what's inside that link:
![1](https://user-images.githubusercontent.com/15570970/95956232-01d29700-0dcc-11eb-814c-9eef1879d63b.jpg)

And also the downloaded file from it:
[transpose.tar.gz](https://github.com/kaldi-asr/kaldi/files/5376322/transpose.tar.gz)

**Comment by danpovey** [comment]
Forget that about the web link.  I think the issue is not transpose after
all.  In AddSmatMat, it doesn't call AccuProfile()
(which would sync the GPU) until after the transposed copy:
    this->CopyFromMat(CT, kTrans);
    CuDevice::Instantiate().AccuProfile(__func__, tim);
(at cu-matrix.cc:1069).    So the apparent CopyFromMat is really the time
taken in AddSmatMat.  That's CuSparse code
so we don't have a lot of control or insight there.

**Comment by qmmn** [comment]
@danpovey 
T___T

**Comment by qmmn** [comment]
@danpovey 
I found a way to workaround that CuSparse slow.
Replacing the parameter value CUSPARSE_MM_ALG_DEFAULT to CUSPARSE_SPMM_CSR_ALG2 in cusparseSpMM_bufferSize/cusparseSpMM, and **AddSMatMat** GPU time reduces from **46.6874s** to **0.469284s**:
```
[cudevice profile]
CuVectorBase::Floor	0.24982s
SymAddMat2	0.281039s
CopyRowsFromVec	0.292883s
AddDiagMatMat	0.320773s
CuVector::Resize	0.322935s
Sum	0.331333s
CuMatrix::Resize	0.332538s
AddSmatMat	0.469284s
AddMat	0.478038s
CuMatrix::SetZero	0.587106s
TraceMatMat	0.676328s
BackpropLstmNonlinearity	0.773163s
CopyToVec	0.818208s
CuMatrixBase::CopyFromMat(from other CuMatrixBase)	1.96195s
AddMatMat	10.9485s
Total GPU time:	21.982s (may involve some double-counting)
```
It seems there's something in the default algorithm (ALG1) of cusparseSpMM that messes with RTX Ampere.
Yet, there might still be something more. An iteration on full dataset now takes 310s compare to 370s of the 2080ti, only 16% faster. It doesn't match the expectation of 2x faster like in the case of chain tdnn training.

Riding on edged codes and devices is pretty rough, I shouldn't have rushed the trade T__T

**Comment by jtrmal** [comment]
Hugo, any ideas or comments on this?
y.

**Comment by danpovey** [comment]
qmmm, perhaps you could make a PR with that change?

**Comment by qmmn** [comment]
@danpovey 
Yessss of course, right away.
