### ISSUE TITLE
kaldi fails to build with openfst-1.8.3

### ISSUE THREAD

**Issue by yurivict** [kaldi-asr/kaldi#4956]
```
In file included from /usr/ports/audio/kaldi/work/kaldi-4a8b7f6/src/matrix/compressed-matrix.cc:22:
In file included from /usr/ports/audio/kaldi/work/kaldi-4a8b7f6/src/matrix/../matrix/compressed-matrix.h:24:
In file included from /usr/ports/audio/kaldi/work/kaldi-4a8b7f6/src/matrix/../matrix/kaldi-matrix.h:29:
In file included from /usr/ports/audio/kaldi/work/kaldi-4a8b7f6/src/matrix/../matrix/matrix-common.h:26:
In file included from /usr/ports/audio/kaldi/work/kaldi-4a8b7f6/src/matrix/../base/kaldi-common.h:35:
In file included from /usr/ports/audio/kaldi/work/kaldi-4a8b7f6/src/matrix/../base/kaldi-error.h:34:
/usr/ports/audio/kaldi/work/kaldi-4a8b7f6/src/matrix/../base/kaldi-types.h:55:10: fatal error: 'fst/types.h' file not found
   55 | #include <fst/types.h>
      |          ^~~~~~~~~~~~~
1 error generated.
```

FreeBSD 14.1

**Comment by msqr1** [comment]
Add to your compilation command line ```-DOPENFST_VER=10803```. We just fake the lack of fst/types.h using our custom one in kaldi-types.h. Specifically, we have this check ```#if OPENFST_VER >= 10800``` to detect if OpenFST is higher than 1.8.0 (doesn't have a fst/types.h anymore). I will get a PR that convert the OpenFST version and add the -D automatically.
@yurivict

**Comment by jtrmal** [comment]
Yeah, but that variable should be already set up automatically, thats why I'm confused. Or is this person also working on the WASM port?

**Comment by danijel3** [comment]
I'd also like to point out that OpenFST doesn't compile with g++-14. Appending `CXX=g++-13` to all the make/configure steps helps this. It would be nice if this was mentioned somewhere.
