### ISSUE TITLE
compile error building tools, about casting to bool

### ISSUE THREAD

**Issue by rain-1** [kaldi-asr/kaldi#941]
Hello, running 'make' inside tools/ I found compile errors like this:

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I./../include -MT text-io.lo -MD -MP -MF .deps/text-io.Tpo -c text-io.cc  -fPIC -DPIC -o .libs/text-io.o
text-io.cc: In function 'bool fst::script::WritePotentials(const string&, const std::vector<fst::script::WeightClass>&)':
text-io.cc:87:15: error: cannot convert 'std::ostream {aka std::basic_ostream<char>}' to 'bool' in initialization
   bool ret = *strm;
               ^~~~
```

just thought I should report it.

**Comment by danpovey** [comment]
You need to report your compiler version when reporting compilation errors.
Do
g++ --version

This is an OpenFst issue, but we should find a way to work around it.

**Comment by ajira86** [comment]
Hello,

I updated my Debian today and tried to compile from fresh sources with the exact same issue.
Here is my compiler version if it could help you.

```
$ g++ --version
g++ (Debian 6.1.1-11) 6.1.1 20160802
```

**Comment by danpovey** [comment]
I assume you are using some bleeding-edge testing version of debian.
You can't really expect things to work when using such new compilers.  You
could try modifying OPENFST_VERSION to 1.4.1 in the Makefile in tools/, I'd
be interested to see if that works.  But we won't put much effort into
supporting this until it makes its way into the stable distributions.

**Comment by ajira86** [comment]
@danpovey I wrote this answer to give you more data on the issue (if it could help).
I'm usually using Ubuntu 14.04 with Kaldi but just making some tests with my personal Debian Stretch.

As you say, using openfst in version 1.4.1 will fix the problem and compilation will succeed to end.
Here is the information I found in Makefile while editing:

```
OPENFST_VERSION = 1.3.4
# Uncomment the next line to build with OpenFst-1.4.1.
# OPENFST_VERSION = 1.4.1
# Note: OpenFst >= 1.4 requires C++11 support, hence you will need to use a
# relatively recent C++ compiler, e.g. gcc >= 4.6, clang >= 3.0.
```

**Comment by danpovey** [comment]
OK, closing the issue for now.
When gcc 6.x use becomes more prevalent we may change the default OpenFst to 1.4.1.
We've been hanging back on the use of C++11, and OpenFst 1.4.1 requires C++11 which is why it's not the default right now.
