### ISSUE TITLE
I have a great effort on win10 gpu kaldi, there is a problem in kaldi-cudamatrix.

### ISSUE THREAD

**Issue by whaozl** [kaldi-asr/kaldi#4114]
I compile separately kaldi-cudamatrix, and:
```
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(244,3): error C2065: “cusparseSpMatDescr_t”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(244,24): error C2065: “matA”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(250,26): error C2065: “matA”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(252,54): error C2065: “CUSPARSE_INDEX_32I”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(253,25): error C2065: “CUSPARSE_INDEX_32I”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(250,7): error C3861: “cusparseCreateCsr”: No identifier found
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(255,3): error C2065: “cusparseDnMatDescr_t”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(255,24): error C2065: “matB”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(258,33): error C2065: “matB”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(259,32): error C2065: “CUSPARSE_ORDER_COL”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(258,12): error C3861: “cusparseCreateDnMat”: No identifier found
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(261,3): error C2065: “cusparseDnMatDescr_t”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(261,24): error C2065: “matC”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(263,28): error C2065: “matC”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(263,57): error C2065: “CUSPARSE_ORDER_COL”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(263,7): error C3861: “cusparseCreateDnMat”: No identifier found
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(267,67): error C2065: “matA”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(267,73): error C2065: “matB”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(268,42): error C2065: “matC”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(268,57): error C2065: “CUSPARSE_MM_ALG_DEFAULT”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(267,12): error C3861: “cusparseSpMM_bufferSize”: No identifier found
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(273,56): error C2065: “matA”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(273,62): error C2065: “matB”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(273,74): error C2065: “matC”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(274,34): error C2065: “CUSPARSE_MM_ALG_DEFAULT”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(273,12): error C3861: “cusparseSpMM”: No identifier found
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(280,33): error C2065: “matA”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(280,12): error C3861: “cusparseDestroySpMat”: No identifier found
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(282,33): error C2065: “matB”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(282,12): error C3861: “cusparseDestroyDnMat”: No identifier found
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(284,33): error C2065: “matC”: Undeclared identifier
1>C:\anjos\vs\kaldi-win\src\cudamatrix\cublas-wrappers.h(284,12): error C3861: “cusparseDestroyDnMat”: No identifier found
```

it is ok on CPU, **but it report above error on GPU**, at the same time,I [write a blog](https://blog.csdn.net/zhulinniao/article/details/106824052) and [kaldi cpu gpu](https://blog.csdn.net/zhulinniao/article/details/106585549) about this.

and, then, find in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\cusparse.h Line7341:
```cpp
#if !defined(_WIN32)
...
...
cusparseStatus_t CUSPARSEAPI
cusparseSpMM(cusparseHandle_t           handle,
             cusparseOperation_t        opA,
             cusparseOperation_t        opB,
             const void*                alpha,
             const cusparseSpMatDescr_t matA,
             const cusparseDnMatDescr_t matB,
             const void*                beta,
             cusparseDnMatDescr_t       matC,
             cudaDataType               computeType,
             cusparseSpMMAlg_t          alg,
             void*                      externalBuffer);
...
...
#endif // !defined(_WIN32)
```
because of undefine **_WIN32**, so cusparseSpMM undefine ... ? this is window cuda bug?

**Comment by danpovey** [comment]
Likely because cusparse.h or whatever its called was not inclded.  Need to know where cublas-wrappers.h was included from when you got the errors.

**Comment by whaozl** [comment]
and, in fact, the cuspare.h should have included. because, for example **cusparseStatus_t** don't have this type error show [https://github.com/kaldi-asr/kaldi/blob/master/src/cudamatrix/cublas-wrappers.h#L207-L231](https://github.com/kaldi-asr/kaldi/blob/master/src/cudamatrix/cublas-wrappers.h#L207-L231).

only this region code( 
[https://github.com/kaldi-asr/kaldi/blob/master/src/cudamatrix/cublas-wrappers.h#L233-L288](https://github.com/kaldi-asr/kaldi/blob/master/src/cudamatrix/cublas-wrappers.h#L233-L288) ) have this error.

and, I find, this region code, use cusparse.h ** #if !defined(_WIN32)  #endif**.

but in the cuspare.sh this region code is gray because of *!defined(_WIN32)**

**Comment by danpovey** [comment]
When the compiler outputs errors it also tells you what compilation command
it was executing.
That was what I was asking.  So I can know in which context it was
included, and what would have been included above it.
It should be fixable by adding includes to that file directly, but I'd like
to understand the problem

**Comment by whaozl** [comment]
Unfortunately, I found the reason:
in the [CUDA_Toolkit_Release_Notes](https://docs.nvidia.com/cuda/archive/10.1/pdf/CUDA_Toolkit_Release_Notes.pdf)
```
3.6.3. CUDA Libraries
‣ The cuSPARSE generic APIs are currently available only for Linux x86_64 (AMD64)
systems. Using these APIs on any other systems will result in compile-time or runtime failures.
```

and, in the cublas-wrapper.h( cusparseSpMatDescr_t, cusparseCreateCsr..) this only support linux, because in the cusparse.h :
```
#if !defined(_WIN32)
typedef enum {
    CUSPARSE_FORMAT_CSR         = 1, ///< Compressed Sparse Row (CSR)
    CUSPARSE_FORMAT_CSC         = 2, ///< Compressed Sparse Column (CSC)
    CUSPARSE_FORMAT_COO         = 3, ///< Coordinate (COO) - Structure of Arrays
    CUSPARSE_FORMAT_COO_AOS     = 4, ///< Coordinate (COO) - Array of Structures
} cusparseFormat_t;
.....
struct cusparseSpVecDescr;
struct cusparseDnVecDescr;
struct cusparseSpMatDescr;
struct cusparseDnMatDescr;
typedef struct cusparseSpVecDescr* cusparseSpVecDescr_t;
typedef struct cusparseDnVecDescr* cusparseDnVecDescr_t;
typedef struct cusparseSpMatDescr* cusparseSpMatDescr_t;
typedef struct cusparseDnMatDescr* cusparseDnMatDescr_t;
.......
#endif
```
this means If it is not on the window platform, then define this SpMM APIs.

**Comment by kkm000** [comment]
I am closing this ticket for now, since it's the CUDA toolkit issue, and beyond our capacity to fix it. If you discover the underlying cause has been resolved, please feel free to ping me, and I'll reopen it.
